
title: 주곰 #Your awesome title
email: joogomsnap@gmail.com #youremail@domain.com
description: > # this means to ignore newlines until "baseurl"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: # the subpath of the site
url: https://joogom.github.io # the base hostname & protocol for your site

permalink: /:year-:month/:title
timezone:

favicon: /assets/img/favicon.ico

google_analytics: #UA—XXXXXXXX-X
disqus_shortname: #disqus shortname
cusdis:
    app_id: #your cusdis app_id

user:
  name: 주곰
  pic: /assets/img/logo2.jpg
  picAlt: "로고"
  job: 코스프레 촬영합니다.
  aboutme: true # comment this out if you don't need the 'about' page.

exclude:
  - README.md
  - LICENSE
  - github
  - Catbook.url
  - old_posts
  - 링크리스트

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comment: false

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown 

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false
